version: '3.8'

services:
  db:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: store_admin
      POSTGRES_PASSWORD: store_admin
      POSTGRES_DB: store_db
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  store:
    build: .
    container_name: store-server
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DEBUG: "False"
      DATABASE_NAME: "store_db"
      DATABASE_USER: "store_admin"
      DATABASE_PASSWORD: "store_admin"
      DATABASE_HOST: "postgres"
      DATABASE_PORT: 5432